$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json
name: heart-failure-inference-env
image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04:latest
conda_file: conda_env.yml
description: Environment for heart failure inference
